### ISSUE TITLE
Facing _reactSpring.useTransition is not a function

### ISSUE THREAD

**Issue by appasaheb4** [catc/react-timekeeper#115]
ERROR
(0 , _reactSpring.useTransition) is not a function
TypeError: (0 , _reactSpring.useTransition) is not a function
    at ClockWrapper (http://localhost:3000/static/js/bundle.js:1251505:54)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:520983:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:525057:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:526350:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:510721:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:510765:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:510822:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:530491:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:529777:16)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:529701:9)
    
    
    please check below ss
    
<img width="1014" alt="Screenshot 2023-12-25 at 6 41 15 PM" src="https://github.com/catc/react-timekeeper/assets/24726539/e00ab852-0b4c-4b4a-93e9-03dd948292ae">

**Comment by olieinykov** [comment]
Encountered the same issue

**Comment by p-pey** [comment]
any update ?

**Comment by vladimir92ua** [comment]
Can be used `"react-timekeeper": "2.1.3"` version. It is working but the 'time picker' has a slight offset of the clock

**Comment by p-pey** [comment]
I downgraded to v2.1.3 and it is working now

**Comment by ParthShindenovus** [comment]
ClockHand.js:125 Uncaught TypeError: Cannot read properties of undefined (reading 'interpolate')
    at ClockHand (ClockHand.js:125:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateFunctionComponent (react-dom.development.js:19588:1)
    at beginWork (react-dom.development.js:21601:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at recoverFromConcurrentError (react-dom.development.js:25850:1)
    at performSyncWorkOnRoot (react-dom.development.js:26096:1)
    
    
    
    
   
  **

```
import TimeKeeper from "react-timekeeper";
import CloseModalHOC from './CloseModalHOC';

const TimePicker = ({ visibility, value, onChangeDate, onChangeTime, onDone, ...props }) => {
  return (
    <CloseModalHOC onClickOutSide={onDone}>
      <div className="position-relative">
        <div className="position-absolute" style={{ bottom: 90 }}>
          {visibility && <TimeKeeper
            time={value}
            onChange={(newTime) => { onChangeDate(newTime.formatted12 , newTime.formatted24)}}
            onDoneClick={onDone}
            hour24Mode={props.hour24Mode ? true : false}
            switchToMinuteOnHourSelect
          />}
        </div>
        {props.children}
      </div>
    </CloseModalHOC>
  )
}
export default TimePicker;
```

**




after changing the version to 2.1.3 i get this errror while click anywhere in timekeeper

**Comment by PawelSiecinski** [comment]
did you get any workaround for this @ParthShindenovus?
